# Model can be "usleep" or "lseqsleepnet"
model: "usleep"

hdf5_base_path: "/com/ecent/NOBACKUP/Big_Sleep_Set/transformed"

hdf5_split_path: "/home/js/repos/common-sleep-data-pipeline/csdp_pipeline/splits/usleep_split.json"

accelerator: "cpu"

train_sets:
  - "abc"
val_sets:
  - "abc"
test_sets:
  - "abc"

gradient_steps: 5
batch_size: 64
num_workers: 1
lr: 0.0001
max_epochs: 2
early_stop_patience: 50

usleep_parameters:
  initial_filters: 5
  complexity_factor: 1.67
  progression_factor: 2

lseq_parameters:
  coming_soon: 0

test_after_train: True
test_only: False

pretrained: False
pretrained_path: "/home/js/repos/common-sleep-data-pipeline/checkpoints/best_usleep_second.ckpt"

neptune:
  logging: False
  existing_run_id: null
  logging_folder: "/com/ecent/NOBACKUP"
  api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5YzViZjJlYy00NDNhLTRhN2EtOGZmYy00NDEzODBmNTgxYzMifQ=="
  project: "NTLAB/bigsleep"
  name: "usleep"
