# Model can be "usleep" or "lseqsleepnet"
model: "lseqsleepnet"

hdf5_base_path: ""

hdf5_split_path: null
create_random_split: True

accelerator: "gpu"

train_sets:
  - "abc"
val_sets:
  - "abc"
test_sets:
  - "abc"

gradient_steps: 5
batch_size: 64
num_workers: 1
lr: 0.0001
max_epochs: 2
early_stop_patience: 50

lr_sched_patience: 50
lr_sched_factor: 0.5
lr_sched_minimum: 0.0000001

usleep_parameters:
  initial_filters: 5
  complexity_factor: 1.67
  progression_factor: 2

lseq_parameters:
  epoch_window_size: 200

test_after_train: True
test_only: False

pretrained: False
pretrained_path: ""

neptune:
  use: False
  existing_run_id: null
  logging_folder: null
  api_key: ""
  project: ""
  name: ""
